from app.db.database import (
    engine,
    AsyncSessionLocal,
    Base,
    init_db,
    get_db,
)

from app.db.models import (
    CachedUTXO,
    Alert,
    UserConfig,
    PrivacyScoreHistory,
    AddressLabel,
    AddressEntity,
    PendingAddressReview,
)

from app.db.crud import (

    create_or_update_utxo,
    get_utxo,
    get_all_utxos,
    delete_utxo,
    create_alert,
    get_alerts,
    mark_alert_read,
    acknowledge_alert,
    get_config,
    set_config,
    save_privacy_score,
    get_privacy_score_history,
    set_address_label,
    get_address_label,
    create_or_update_entity,
    get_entity,
    get_all_entities,
    delete_entity,
    search_entities,
    # Pending address review
    queue_address_for_review,
    get_pending_reviews,
    get_pending_review,
    label_pending_review,
    dismiss_pending_review,
    count_pending_reviews,
)

__all__ = [
    "engine",
    "AsyncSessionLocal",
    "Base",
    "init_db",
    "get_db",
    "CachedUTXO",
    "Alert",
    "UserConfig",
    "PrivacyScoreHistory",
    "AddressLabel",
    "AddressEntity",
    "PendingAddressReview",
    "create_or_update_utxo",
    "get_utxo",
    "get_all_utxos",
    "delete_utxo",
    "create_alert",
    "get_alerts",
    "mark_alert_read",
    "acknowledge_alert",
    "get_config",
    "set_config",
    "save_privacy_score",
    "get_privacy_score_history",
    "set_address_label",
    "get_address_label",
    "create_or_update_entity",
    "get_entity",
    "get_all_entities",
    "delete_entity",
    "search_entities",
    "queue_address_for_review",
    "get_pending_reviews",
    "get_pending_review",
    "label_pending_review",
    "dismiss_pending_review",
    "count_pending_reviews",
]
